<?php

use Drupal\Core\Form\FormStateInterface;
use Drupal\Core\Mail\MailManagerInterface;

/**
 * @file
 * Primary module hooks for ISED Publications module.
 */

/**
 * Implements hook_form_alter().
 *
 * Allows customization of publication forms.
 */
function ised_publications_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id === 'node_publication_form') {

    \Drupal::messenger()->addMessage("TODO - add conditional validation to 'Other' fields + their matching dropdowns");
    \Drupal::messenger()->addMessage("TODO - fix inline formatting for estimated release date month and year");

    // Bind custom validation
    $form['#validate'][] = 'ised_publications_node_create_validation';

    // Add the prefix / preamble 
    $form['group_ised_contact_information']['#prefix'] = '<div class="publications-form-preamble">';
    $form['group_ised_contact_information']['#prefix'] .= '<span class="required-red-star">*</span>' . t('Indicates required information');
    $form['group_ised_contact_information']['#prefix'] .= '<p>' . t('Do not use the "back" button to fill out multiple forms.') .'</p>';

    $form['group_ised_contact_information']['#prefix'] .= '</div>';

    $form['group_ised_contact_information']['#prefix'] .= '<div><p><strong>';
    $form['group_ised_contact_information']['#prefix'] .=  t('Purpose');
    $form['group_ised_contact_information']['#prefix'] .=  ': </strong>';

    $form['group_ised_contact_information']['#prefix'] .= t('For monograph (single publication), new and existing series');

    $form['group_ised_contact_information']['#prefix'] .= '</p><p>';
    $form['group_ised_contact_information']['#prefix'] .= t('Your application wil be sent to the <a href="http://publications.gc.ca/site/eng/programs/aboutDsp.html" title="Depository Services Program" target="_blank">Depository Services Program</a> at Public Services and Procurement.  The ISBN and Cataloge Number will be emailed to you and Creative Services within three business days, provided that there are no problems with the application.');
    $form['group_ised_contact_information']['#prefix'] .= '</p></div><br/><br/>';

    // Tweak inline form fields so their labels appear beside the field, not beneath the field
    $form['field_contact_person']['#attributes']['class'][] = 'container-inline';
    $form['field_email']['#attributes']['class'][] = 'container-inline';
    $form['field_telephone']['#attributes']['class'][] = 'container-inline';

    $form['#attached']['library'][] = 'ised_publications/node_form_publication';

    // If user is anonymous, hide things we don't want them to see
    $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    if ($user->id() == 0) {
      $form['revision_information']['#access'] = FALSE;
      $form['moderation_state']['#access'] = FALSE;
    }
    // Bind our custom message grooming handler
    foreach (array_keys($form['actions']) as $action) {
      if ($action != 'preview' && isset($form['actions'][$action]['#type']) && $form['actions'][$action]['#type'] === 'submit') {
        $form['actions'][$action]['#submit'][] = 'ised_publications_message_grooming_handler';
      }
    }
  }
}

/**
 * Implements hook_preprocess_preprocess_page_title().
 *
 * Set some overrides for the page title when creating a new publication 
 */
function ised_publications_preprocess_page_title(&$variables) {

  if ($variables['title'] == 'Create Publication') {
    $variables['title'] = 'Form 1 -- Application for ISBN and/or GC Catalogue Number via Innovation, Science and Economic Development Canada';
  }
}

/**
 * Implements hook_entity_insert().
 */
function ised_publications_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {

  $bundle = $entity->bundle();

  if ($bundle == 'publication') {

    $recipientsTo = \Drupal::config('ised_publications.settings')->get('form_1_email_notice_recipients');
    $recipientsCC = \Drupal::config('ised_publications.settings')->get('form_1_email_notice_recipients_cc');

    $subject = 'Application for ISBN and Cat. No - Demande de ISBN et de No de cat. / ICWE-BVVS3P';
    $contactPerson = $entity->field_contact_person->getString();
    $telephone = $entity->field_telephone->getString();
    $email = $entity->field_email->getString();

    $sectorBranchOrAgency = $entity->field_choose_sector_branch_or_ag->getString();
    $sectorBranchOrAgencyOther = $entity->field_if_other_is_selected_indic->getString();
    $freeOrPriced = $entity->field_this->getString();
    $englishTitle = $entity->title->getString();
    $frenchTitle = $entity->field_title_french->getString();
    $languageOfPublication = $entity->field_language_of_publication->getString();
    $languageOfPublicationOther = $entity->field_lang_of_pub_other->getString();
    $publicationFormats = $entity->field_publication_formats->getString();
    $anticipatedReleaseMonth = $entity->field_anticipated_release_date_m->getString();
    $anticpatedReleaseYear = $entity->field_anticipated_release_date_y->getString();
    $typeOfPublication = $entity->field_type_of_publication->getString();
    $seriesTitleEnglish = $entity->field_series_title_english->getString();
    $seriesTitleFrench = $entity->field_series_title_french->getString();
    $issn =  $entity->field_issn->getString();
    $issueNumber = $entity->field_issue_number->getString();
    $comments = $entity->field_comments->getString();

    $hasFileAttachment = '';

    if (@is_array($entity->field_pdf_document->getValue()[0])) {

      $fid = $entity->field_pdf_document->getValue()[0]['target_id'];

      if (is_numeric($fid) && $fid > 0) {
        $file = \Drupal\file\Entity\File::load($fid);
        $hasFileAttachment = t('Yes'); 
        $hasFileAttachment .= ' (' . $file->getFilename() .')';
      }
    }
    else {

      $hasFileAttachment = t('No');
    }

    $message = "ICCAT-ID: ICWE-BVVS3P

Issuing Agency:  Innovation, Science and Economic Development Canada
Contact Person: $contactPerson
Telephone: $telephone
Email: $email

Choose Sector, Branch or Agency: $sectorBranchOrAgency
If 'Other' is selected, indicate title of working group, panel or committee: $sectorBranchOrAgencyOther


This publication is: $freeOrPriced

English title: $englishTitle
French title: $frenchTitle

Language: $languageOfPublication
If 'Other' is selected, specify language of publication and quantity published (if printed): $languageOfPublicationOther

Publication formats: $publicationFormats

Anticipated Release Month: $anticipatedReleaseMonth Anticipated Release Year: $anticpatedReleaseYear

Type of Publication: $typeOfPublication

Series title - English: $seriesTitleEnglish
Series title - French: $seriesTitleFrench
ISSN:  $issn
Issue Number: $issueNumber

Comments:
$comments

Has file attachment? $hasFileAttachment

";

  $mailManager = \Drupal::service('plugin.manager.mail');
  $module = 'ised_publications';
  $key = 'ised_publications_form_1_submit_notification'; 
  $to = $email . ',' . $recipientsTo;
  $params['body'] = $message;
  $params['subject'] = $subject;
  $params['cc'] = $recipientsCC;

  $langcode = 'en';

  $result = $mailManager->mail($module, $key, $to, $langcode, $params);

  if ($result['result'] != true) {
      $message = t('There was a problem sending your email notification to @email.', array('@email' => $to));
      drupal_set_message($message, 'error');
      \Drupal::logger('mail-log')->error($message . ' result:  ' . json_encode($result));
      return;
    }
    else {
      \Drupal::messenger()->addMessage(t('Thank you for your submission.  A copy of the information you submitted for this publication was also sent to you by email at %email', ['%email' => $to]));
    }
  }
}

/**
 * Implements hook_mail().
 */
function ised_publications_mail($key, &$message, $params) {

  if ($key == 'ised_publications_form_1_submit_notification') {

    \Drupal::logger('ised_publications')->notice('Attempting to send mail...');

      $message['headers']['cc'] = $params['cc'];
      $message['subject'] = $params['subject'];
      $message['reply-to'] = 'donotreply-drupal-nepasrepondre@ised-isde.canada.ca';
      $message['body'][] = $params['body'];
  }
}

/**
 * Modify the message stack to remove default content creation message.
 */
function ised_publications_message_grooming_handler(&$form, \Drupal\Core\Form\FormStateInterface $form_state) { // Drupal 8

  $messages = \Drupal::messenger()->all();
 
  // Remove all messages (but not errors)
  \Drupal::messenger()->deleteAll();
  foreach( $messages as $type => $msglist) {
    if($type == 'error') { 
      foreach($msglist as $errmsg) {
        \Drupal::messenger()->addError($errmsg);
      }
    }
  }

  // Add back our customized publication created message
  \Drupal::messenger()->addMessage(t('Thank you for your submission. You will receive a copy of the information you submitted by email.'));
}

/**
 * Custom validation functionality for node create publication form.
 */
function ised_publications_node_create_validation($form, &$form_state) {

  // If user selects value "other" for "Choose Sector, Branch or Agency"
  // they must also provide a string for the matching "other" field
 if ($form_state->hasValue('field_choose_sector_branch_or_ag')) {

    $branchOrAgency = $form_state->getValue('field_choose_sector_branch_or_ag')[0]['value'];
    if ($branchOrAgency == t('Other')) {
      $otherBranchOrAgency = $form_state->getValue('field_if_other_is_selected_indic')[0]['value'];
      if ($otherBranchOrAgency == '') {
        $form_state->setErrorByName('field_if_other_is_selected_indic', t('If you select "other" from the Sector, Branch or Agency dropdown you must provide a value for this field'));
      }
    }

 }
}