<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * @file
 * Primary module hooks for ISED Publications module.
 */

/**
 * Implements hook_form_alter().
 *
 * Allows customization of publication forms.
 */
function ised_publications_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id === 'node_publication_form') {

    \Drupal::messenger()->addMessage("TODO - add conditional validation to 'Other' fields + their matching dropdowns");
    \Drupal::messenger()->addMessage("TODO - fix inline formatting for estimated release date month and year");
    \Drupal::messenger()->addMessage("TODO - remove revision log entry for anon user");

    // Add the prefix / preamble 
    $form['group_ised_contact_information']['#prefix'] = '<div class="publications-form-preamble">';
    $form['group_ised_contact_information']['#prefix'] .= '<span class="required-red-star">*</span>' . t('Indicates required information');
    $form['group_ised_contact_information']['#prefix'] .= '<p>' . t('Do not use the "back" button to fill out multiple forms.') .'</p>';

    $form['group_ised_contact_information']['#prefix'] .= '</div>';

    $form['group_ised_contact_information']['#prefix'] .= '<div><br/><p><strong>';
    $form['group_ised_contact_information']['#prefix'] .=  t('Purpose');
    $form['group_ised_contact_information']['#prefix'] .=  ': </strong>';

    $form['group_ised_contact_information']['#prefix'] .= t('For monograph (single publication), new and existing series');

    $form['group_ised_contact_information']['#prefix'] .= '</p><p>';
    $form['group_ised_contact_information']['#prefix'] .= t('Your application wil be sent to the <a href="http://publications.gc.ca/site/eng/programs/aboutDsp.html" target="_blank">Depository Services Program</a> at Public Services and Procurement.  The ISBN and Cataloge Number will be emailed to you and Creative Services within three business days, provided that there are no problems with the application.');
    $form['group_ised_contact_information']['#prefix'] .= '</p></div><br/><br/>';

    // Tweak inline form fields so their labels appear beside the field, not beneath the field
    $form['field_contact_person']['#attributes']['class'][] = 'container-inline';
    $form['field_email']['#attributes']['class'][] = 'container-inline';
    $form['field_telephone']['#attributes']['class'][] = 'container-inline';

    $form['#attached']['library'][] = 'ised_publications/node_form_publication';

    // If user is anonymous, hide things we don't want them to see
    $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
    if ($user->id() == 0) {
      $form['revision_information']['#access'] = FALSE;
      $form['moderation_state']['#access'] = FALSE;
    }
  }
}


/**
 * Implements hook_preprocess_preprocess_page_title().
 * 
 * Set some overrides for the page title when creating a new publication 
 */
function ised_publications_preprocess_page_title(&$variables) {

  if ($variables['title'] == 'Create Publication') {
    $variables['title'] = 'Form 1 -- Application for ISBN and/or GC Catalogue Number via Innovation, Science and Economic Development Canada';
  }
}

/**
 * Implements hook_entity_insert()
 */
function ised_publications_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {

  $bundle = $entity->bundle();
  
  if($bundle == 'publication') {
    $recipientsRaw = \Drupal::config('ised_publications.settings')->get('form_1_email_notice_recipients');
    \Drupal::messenger()->addMessage("SEE ITEM OF bundle type $bundle READY TO SEND NOTIFICATION TO $recipientsRaw");

    $subject = 'Application for ISBN and Cat. No - Demande de ISBN et de o de cat. / ICWE-BVVS3P';
    $contactPerson = $entity->field_contact_person->getString();
    
  //  $telephone = $entity->get('field_telephone')->value();
   // $email = $entity->get('field_email')->value();

    // Need iterator
//    $sectorBranchOrAgency = $entity->get('field_choose_sector_branch_or_ag')->value();



    
    /*


$sectorBranchOrAgencyOther
$freeOrPriced
$englishTitle
$frenchTitle
$languageOfPublication
$languageOfPublicationOther
$publicationFormats
$anticipatedReleaseMonth
$anticpatedReleaseYear
$typeOfPublication 
$seriesTitleEnglish
$seriesTitleFrench
$issn
$issueNumber
$comments
$hasFileAttachment
    */

    $message = "ICCAT-ID: ICWE-BVVS3P

Issuing Agency:  Innovation, Science and Economic Development Canada
Contact Person: $contactPerson
Telephone: $telephone
Email: $email

Choose Sector, Branch or Agency: $sectorBranchOrAgency
If 'Other' is selected, indicate title of working group, panel or committee: $sectorBranchOrAgencyOther


This publication is: $freeOrPriced

English title: $englishTitle
French title: $frenchTitle

Language: $languageOfPublication
If 'Other' is selected, specify language of publication and quantity published (if printed): $languageOfPublicationOther

Publication formats: $publicationFormats

Anticipated Release Month: $anticipatedReleaseMonth Anticipated Release Year: $anticpatedReleaseYear

Type of Publication: $typeOfPublication

Series title - English: $seriesTitleEnglish
Series title - French: $seriesTitleFrench
ISSN:  $issn
Issue Number: $issueNumber

Comments:
$comments

Has file attachment? $hasFileAttachment




";


  \Drupal::logger('ised_publications')->notice("Created email: $message");


  }
}


